using System.Collections.Generic;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using MessagingByteSerialization.Generators.Model;

namespace MessagingByteSerialization.Generators.Emit;

/// <summary>
/// Emits a single static <c>ByteSerializableFactory</c> aggregating every <c>[ByteSerializable]</c> type
/// that was successfully analyzed in the current compilation. <c>Serialize</c> writes a
/// [2-byte TypeHash][payload] envelope for any <c>IByteSerializable&lt;T&gt;</c> value; <c>TryDeserialize</c>
/// reads that same envelope and dispatches to the matching type's <c>FromBytes</c>. Plain
/// <c>ToBytes()</c>/<c>FromBytes()</c> on a type do NOT include this prefix - it only exists in the
/// envelope produced by <c>Serialize</c>, since a lone payload is not self-describing.
///
/// This only ever sees types declared (and marked) in the current compilation - source generators do not
/// see referenced assemblies' syntax - so messages meant to be dispatchable together should live in one
/// assembly.
/// </summary>
internal static class FactoryEmitter
{
    public const string FactoryClassName = "ByteSerializableFactory";

    public static string? Emit(ImmutableArray<TypeModel> models, List<Diagnostic> diagnostics)
    {
        if (models.IsDefaultOrEmpty)
        {
            return null;
        }

        var seenHashes = new Dictionary<ushort, TypeModel>();
        var usable = new List<TypeModel>();

        foreach (TypeModel model in models)
        {
            if (seenHashes.TryGetValue(model.TypeHash, out TypeModel? existing))
            {
                diagnostics.Add(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateTypeHash,
                    Location.None,
                    existing.FullyQualifiedName,
                    model.FullyQualifiedName,
                    model.TypeHash));
                continue;
            }

            seenHashes[model.TypeHash] = model;
            usable.Add(model);
        }

        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();

        using (w.Block("namespace MessagingByteSerialization.Generated"))
        {
            using (w.Block($"public static class {FactoryClassName}"))
            {
                EmitSerialize(w);
                w.Line();
                EmitTryDeserialize(w, usable);
            }
        }

        return w.ToString();
    }

    private static void EmitSerialize(CodeWriter w)
    {
        w.Line("/// <summary>Number of bytes <see cref=\"Serialize{T}(T, global::System.Span{byte})\"/> will write for <paramref name=\"message\"/>: the 2-byte TypeHash prefix plus its payload.</summary>");
        using (w.Block("public static int GetEnvelopeSize<T>(T message) where T : global::MessagingByteSerialization.IByteSerializable<T>"))
        {
            w.Line("return 2 + message.GetByteSize();");
        }

        w.Line();
        w.Line("/// <summary>Writes the [2-byte TypeHash][payload] envelope that <see cref=\"TryDeserialize\"/> expects. <paramref name=\"destination\"/> must be at least <see cref=\"GetEnvelopeSize{T}(T)\"/> bytes long.</summary>");
        using (w.Block("public static void Serialize<T>(T message, global::System.Span<byte> destination) where T : global::MessagingByteSerialization.IByteSerializable<T>"))
        {
            w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination, T.TypeHash);");
            w.Line("message.ToBytes(destination.Slice(2));");
        }

        w.Line();
        w.Line("/// <summary>Convenience allocation for callers outside a hot path. Prefer <see cref=\"Serialize{T}(T, global::System.Span{byte})\"/>.</summary>");
        using (w.Block("public static byte[] Serialize<T>(T message) where T : global::MessagingByteSerialization.IByteSerializable<T>"))
        {
            w.Line("byte[] buffer = new byte[GetEnvelopeSize(message)];");
            w.Line("Serialize(message, buffer);");
            w.Line("return buffer;");
        }
    }

    private static void EmitTryDeserialize(CodeWriter w, List<TypeModel> models)
    {
        w.Line("/// <summary>");
        w.Line("/// Reads a leading little-endian TypeHash prefix from <paramref name=\"source\"/> and dispatches to the");
        w.Line("/// matching [ByteSerializable] type's FromBytes. Returns false (without throwing) for an unknown or too-short prefix.");
        w.Line("/// </summary>");
        using (w.Block("public static bool TryDeserialize(global::System.ReadOnlySpan<byte> source, out global::MessagingByteSerialization.IByteSerializable? message, out int bytesRead)"))
        {
            using (w.Block("if (source.Length < 2)"))
            {
                w.Line("message = null;");
                w.Line("bytesRead = 0;");
                w.Line("return false;");
            }

            w.Line();
            w.Line("ushort typeHash = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source);");
            w.Line("global::System.ReadOnlySpan<byte> payload = source.Slice(2);");
            w.Line();

            using (w.Block("switch (typeHash)"))
            {
                foreach (TypeModel model in models)
                {
                    using (w.Block($"case {model.TypeHash}:"))
                    {
                        w.Line($"message = {model.FullyQualifiedName}.FromBytes(payload, out int typeBytesRead);");
                        w.Line("bytesRead = typeBytesRead + 2;");
                        w.Line("return true;");
                    }
                }

                using (w.Block("default:"))
                {
                    w.Line("message = null;");
                    w.Line("bytesRead = 0;");
                    w.Line("return false;");
                }
            }
        }
    }
}
