using System.Linq;
using MessagingByteSerialization.Generators.Model;

namespace MessagingByteSerialization.Generators.Emit;

/// <summary>
/// Renders the generated partial declaration implementing <c>IByteSerializable&lt;TSelf&gt;</c> for one
/// analyzed <see cref="TypeModel"/>: <c>TypeHash</c>, <c>GetByteSize</c>, <c>ToBytes</c> and
/// <c>FromBytes</c>.
///
/// Members are always processed in declaration order (required for ToBytes/FromBytes wire
/// compatibility); a single running <c>offset</c> local tracks the write/read cursor. Fixed-size
/// members advance <c>offset</c> by a compile-time literal with no runtime size lookup; only
/// variable-size members (collections, strings, and nested variable-size types) call GetByteSize/read a
/// runtime count. GetByteSize itself is order-independent (summation), so it folds every fixed member
/// into one literal and only emits runtime expressions for the variable ones.
///
/// List/array items can themselves be nested List/array collections (List&lt;List&lt;T&gt;&gt;, T[][],
/// arbitrary combinations/depths). Each nested item is fully self-delimiting - it carries its own
/// [kind][item type code][count] header - so read/write/size all just recurse. The one thing that needs
/// explicit bookkeeping across recursion is naming: a `for` loop index variable or size accumulator local
/// declared at one nesting depth would collide with the same fixed name at another depth if they end up
/// lexically nested (CS0136), so a `depth` parameter is threaded through every recursive call purely to
/// keep generated identifiers like `i0`/`i1` or `itemsSize0`/`itemsSize1` unique per level.
/// </summary>
internal static class SourceEmitter
{
    public static string Emit(TypeModel model)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line();

        if (model.Namespace.Length > 0)
        {
            using (w.Block($"namespace {model.Namespace}"))
            {
                EmitType(w, model);
            }
        }
        else
        {
            EmitType(w, model);
        }

        return w.ToString();
    }

    private static void EmitType(CodeWriter w, TypeModel model)
    {
        using (w.Block($"{model.DeclarationHeader} {model.Name} : global::MessagingByteSerialization.IByteSerializable<{model.FullyQualifiedName}>"))
        {
            w.Line($"public static ushort TypeHash => {model.TypeHash};");
            w.Line();
            EmitGetByteSize(w, model);
            w.Line();
            EmitToBytes(w, model);
            w.Line();
            EmitToBytesArrayConvenience(w);
            w.Line();
            EmitFromBytes(w, model);
            w.Line();
            EmitFromBytesArrayConvenience(w, model);
        }
    }

    private static void EmitToBytesArrayConvenience(CodeWriter w)
    {
        // A plain instance method, not a default interface member: C# only resolves default interface
        // members through an interface-typed expression, never through the concrete type's own name, so
        // a default implementation on IByteSerializable would make `instance.ToBytes()` fail to compile.
        w.Line("/// <summary>Convenience allocation for callers outside a hot path. Prefer <see cref=\"ToBytes(global::System.Span{byte})\"/>.</summary>");
        using (w.Block("public byte[] ToBytes()"))
        {
            w.Line("byte[] buffer = new byte[GetByteSize()];");
            w.Line("ToBytes(buffer);");
            w.Line("return buffer;");
        }
    }

    private static void EmitFromBytesArrayConvenience(CodeWriter w, TypeModel model)
    {
        w.Line("/// <summary>Convenience overload for callers outside a hot path. Prefer <see cref=\"FromBytes(global::System.ReadOnlySpan{byte}, out int)\"/>.</summary>");
        w.Line($"public static {model.FullyQualifiedName} FromBytes(byte[] source) => FromBytes(global::System.MemoryExtensions.AsSpan(source), out _);");
    }

    // ----------------------------------------------------------------- GetByteSize

    private static void EmitGetByteSize(CodeWriter w, TypeModel model)
    {
        if (model.IsFixedSize)
        {
            w.Line($"public const int FixedByteSize = {model.FixedSize};");
            w.Line();
            w.Line("public int GetByteSize() => FixedByteSize;");
            return;
        }

        using (w.Block("public int GetByteSize()"))
        {
            int fixedPrefix = model.Members.Where(static m => !m.IsIgnored && !m.IsVariableSize).Sum(static m => m.Scalar!.FixedSize);
            w.Line($"int size = {fixedPrefix};");

            foreach (MemberModel member in model.Members.Where(static m => !m.IsIgnored && m.IsVariableSize))
            {
                EmitSizeContribution(w, member);
            }

            w.Line("return size;");
        }
    }

    private static void EmitSizeContribution(CodeWriter w, MemberModel member)
    {
        string accessor = MemberAccessor(member);
        switch (member.Shape)
        {
            case MemberShape.String:
                w.Line($"size += global::System.Text.Encoding.UTF8.GetByteCount({accessor}) + 5;");
                break;

            case MemberShape.List:
            case MemberShape.Array:
                string countExpr = member.Shape == MemberShape.List ? $"{accessor}.Count" : $"{accessor}.Length";
                EmitCollectionSizeContribution(w, member.Element!, accessor, countExpr, "size", depth: 0);
                break;

            case MemberShape.Dictionary:
                if (member.Key!.IsFixedSize && member.DictionaryValue!.IsFixedSize)
                {
                    w.Line($"size += 9 + {accessor}.Count * ({member.Key.FixedSize} + {member.DictionaryValue.FixedSize});");
                }
                else
                {
                    using (w.Scope())
                    {
                        w.Line("int entriesSize = 0;");
                        using (w.Block($"foreach (var entry in {accessor})"))
                        {
                            w.Line($"entriesSize += {ScalarSizeExpr(member.Key!, "entry.Key")};");

                            if (member.DictionaryValue!.Shape == ItemShape.Scalar)
                            {
                                w.Line($"entriesSize += {ScalarSizeExpr(member.DictionaryValue.Scalar!, "entry.Value")};");
                            }
                            else
                            {
                                string valueCountExpr = member.DictionaryValue.Shape == ItemShape.Array ? "entry.Value.Length" : "entry.Value.Count";
                                EmitCollectionSizeContribution(w, member.DictionaryValue.Element!, "entry.Value", valueCountExpr, "entriesSize", depth: 0);
                            }
                        }

                        w.Line("size += 9 + entriesSize;");
                    }
                }

                break;

            case MemberShape.Scalar:
                // Only reachable for a variable-size nested IByteSerializable member.
                w.Line($"size += {accessor}.GetByteSize();");
                break;
        }
    }

    /// <summary>
    /// Emits statements that add the wire size of the List/array at <paramref name="accessor"/> (with
    /// <paramref name="countExpr"/> items of type <paramref name="item"/>) into <paramref name="accumulatorVar"/>.
    /// Recurses when <paramref name="item"/> is itself a nested collection - each level gets its own
    /// depth-suffixed accumulator/loop-variable names so nested blocks never redeclare a sibling's locals.
    /// </summary>
    private static void EmitCollectionSizeContribution(CodeWriter w, ItemTypeModel item, string accessor, string countExpr, string accumulatorVar, int depth)
    {
        if (item.IsFixedSize)
        {
            w.Line($"{accumulatorVar} += 7 + {countExpr} * {item.FixedSize};");
            return;
        }

        using (w.Scope())
        {
            string itemsSizeVar = $"itemsSize{depth}";
            string loopVar = $"nestedItem{depth}";
            w.Line($"int {itemsSizeVar} = 0;");

            using (w.Block($"foreach (var {loopVar} in {accessor})"))
            {
                if (item.Shape == ItemShape.Scalar)
                {
                    w.Line($"{itemsSizeVar} += {ScalarSizeExpr(item.Scalar!, loopVar)};");
                }
                else
                {
                    string nestedCountExpr = item.Shape == ItemShape.Array ? $"{loopVar}.Length" : $"{loopVar}.Count";
                    EmitCollectionSizeContribution(w, item.Element!, loopVar, nestedCountExpr, itemsSizeVar, depth + 1);
                }
            }

            w.Line($"{accumulatorVar} += 7 + {itemsSizeVar};");
        }
    }

    /// <summary>Runtime size (in bytes) of a single scalar collection item / dictionary key or value whose own type is not fixed-size.</summary>
    private static string ScalarSizeExpr(ScalarTypeModel scalar, string accessor) => scalar.Kind switch
    {
        ScalarKind.String => $"global::System.Text.Encoding.UTF8.GetByteCount({accessor}) + 4",
        _ when scalar.IsFixedSize => scalar.FixedSize.ToString(),
        _ => $"{accessor}.GetByteSize()",
    };

    // ----------------------------------------------------------------- ToBytes

    private static void EmitToBytes(CodeWriter w, TypeModel model)
    {
        using (w.Block("public void ToBytes(global::System.Span<byte> destination)"))
        {
            MemberModel[] writable = model.Members.Where(static m => !m.IsIgnored).ToArray();
            if (writable.Length == 0)
            {
                return;
            }

            w.Line("int offset = 0;");
            foreach (MemberModel member in writable)
            {
                EmitWriteMember(w, member);
            }
        }
    }

    private static void EmitWriteMember(CodeWriter w, MemberModel member)
    {
        string accessor = MemberAccessor(member);
        switch (member.Shape)
        {
            case MemberShape.Scalar:
                EmitWriteScalar(w, member.Scalar!, accessor);
                break;
            case MemberShape.String:
                EmitWriteString(w, accessor);
                break;
            case MemberShape.List:
                EmitWriteCollection(w, member.Element!, accessor, "global::MessagingByteSerialization.CollectionKind.List", isArray: false, depth: 0);
                break;
            case MemberShape.Array:
                EmitWriteCollection(w, member.Element!, accessor, "global::MessagingByteSerialization.CollectionKind.Array", isArray: true, depth: 0);
                break;
            case MemberShape.Dictionary:
                EmitWriteDictionary(w, member.Key!, member.DictionaryValue!, accessor);
                break;
        }
    }

    private static void EmitWriteScalar(CodeWriter w, ScalarTypeModel scalar, string accessor)
    {
        if (scalar.Kind == ScalarKind.NestedByteSerializable)
        {
            w.Line($"{accessor}.ToBytes(destination.Slice(offset));");
            w.Line(scalar.NestedIsFixedSize ? $"offset += {scalar.NestedFixedSize};" : $"offset += {accessor}.GetByteSize();");
            return;
        }

        if (scalar.Kind == ScalarKind.String)
        {
            EmitWriteLengthPrefixedString(w, accessor);
            return;
        }

        string valueExpr = scalar.Kind == ScalarKind.Enum ? $"({ClrKeyword(scalar.Primitive)}){accessor}" : accessor;
        EmitWritePrimitive(w, scalar.Primitive, valueExpr);
    }

    private static void EmitWritePrimitive(CodeWriter w, PrimitiveKind kind, string valueExpr)
    {
        switch (kind)
        {
            case PrimitiveKind.Boolean:
                w.Line($"destination[offset] = (byte)({valueExpr} ? 1 : 0);");
                break;
            case PrimitiveKind.Byte:
                w.Line($"destination[offset] = {valueExpr};");
                break;
            case PrimitiveKind.SByte:
                w.Line($"destination[offset] = unchecked((byte){valueExpr});");
                break;
            case PrimitiveKind.Char:
                w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination.Slice(offset), {valueExpr});");
                break;
            case PrimitiveKind.Decimal:
                using (w.Scope())
                {
                    w.Line("global::System.Span<int> bits = stackalloc int[4];");
                    w.Line($"decimal.GetBits({valueExpr}, bits);");
                    w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset), bits[0]);");
                    w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset + 4), bits[1]);");
                    w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset + 8), bits[2]);");
                    w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset + 12), bits[3]);");
                }

                break;
            case PrimitiveKind.Guid:
                w.Line($"{valueExpr}.TryWriteBytes(destination.Slice(offset));");
                break;
            case PrimitiveKind.DateTime:
                // ToBinary()/FromBinary() round-trips DateTimeKind (Local/Utc/Unspecified) too, unlike raw Ticks.
                w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(destination.Slice(offset), {valueExpr}.ToBinary());");
                break;
            case PrimitiveKind.TimeOnly:
                w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(destination.Slice(offset), {valueExpr}.Ticks);");
                break;
            default:
                w.Line($"global::System.Buffers.Binary.BinaryPrimitives.Write{kind}LittleEndian(destination.Slice(offset), {valueExpr});");
                break;
        }

        w.Line($"offset += {kind.Size()};");
    }

    private static void EmitWriteString(CodeWriter w, string accessor)
    {
        w.Line("destination[offset] = (byte)global::MessagingByteSerialization.CollectionKind.String;");
        w.Line("offset += 1;");
        EmitWriteLengthPrefixedString(w, accessor);
    }

    /// <summary>[4-byte UTF8 byte count][UTF8 bytes] - shared by top-level string members (after their
    /// leading CollectionKind byte) and by List&lt;string&gt;/string[] items (which have no marker byte,
    /// since the collection's own item type code already says "string").</summary>
    private static void EmitWriteLengthPrefixedString(CodeWriter w, string accessor)
    {
        using (w.Scope())
        {
            w.Line($"int byteCount = global::System.Text.Encoding.UTF8.GetByteCount({accessor});");
            w.Line("global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset), byteCount);");
            w.Line("offset += 4;");
            w.Line($"global::System.Text.Encoding.UTF8.GetBytes({accessor}, destination.Slice(offset, byteCount));");
            w.Line("offset += byteCount;");
        }
    }

    private static void EmitWriteCollection(CodeWriter w, ItemTypeModel item, string accessor, string kindConstant, bool isArray, int depth)
    {
        w.Line($"destination[offset] = (byte){kindConstant};");
        w.Line("offset += 1;");
        w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination.Slice(offset), {ItemTypeCodeExpr(item)});");
        w.Line("offset += 2;");

        string countExpr = isArray ? $"{accessor}.Length" : $"{accessor}.Count";
        w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset), {countExpr});");
        w.Line("offset += 4;");

        string indexVar = $"i{depth}";
        using (w.Block($"for (int {indexVar} = 0; {indexVar} < {countExpr}; {indexVar}++)"))
        {
            EmitWriteItem(w, item, $"{accessor}[{indexVar}]", depth + 1);
        }
    }

    /// <summary>Writes a single List/array item, recursing into <see cref="EmitWriteCollection"/> when the item is itself a nested collection.</summary>
    private static void EmitWriteItem(CodeWriter w, ItemTypeModel item, string accessor, int depth)
    {
        if (item.Shape == ItemShape.Scalar)
        {
            EmitWriteScalar(w, item.Scalar!, accessor);
            return;
        }

        bool isArray = item.Shape == ItemShape.Array;
        string kindConstant = isArray ? "global::MessagingByteSerialization.CollectionKind.Array" : "global::MessagingByteSerialization.CollectionKind.List";
        EmitWriteCollection(w, item.Element!, accessor, kindConstant, isArray, depth);
    }

    private static void EmitWriteDictionary(CodeWriter w, ScalarTypeModel key, ItemTypeModel value, string accessor)
    {
        w.Line("destination[offset] = (byte)global::MessagingByteSerialization.CollectionKind.Dictionary;");
        w.Line("offset += 1;");
        w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination.Slice(offset), {ScalarTypeCodeExpr(key)});");
        w.Line("offset += 2;");
        w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(destination.Slice(offset), {ItemTypeCodeExpr(value)});");
        w.Line("offset += 2;");
        w.Line($"global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(destination.Slice(offset), {accessor}.Count);");
        w.Line("offset += 4;");

        using (w.Block($"foreach (var entry in {accessor})"))
        {
            EmitWriteScalar(w, key, "entry.Key");
            EmitWriteItem(w, value, "entry.Value", depth: 0);
        }
    }

    private static string ScalarTypeCodeExpr(ScalarTypeModel scalar) => scalar.Kind switch
    {
        ScalarKind.FixedPrimitive or ScalarKind.Enum => $"global::MessagingByteSerialization.WellKnownTypeCodes.{scalar.Primitive.WellKnownCodeConstantName()}",
        ScalarKind.NestedByteSerializable => $"{scalar.NestedTypeFullName}.TypeHash",
        ScalarKind.String => "global::MessagingByteSerialization.WellKnownTypeCodes.String",
        _ => "0",
    };

    /// <summary>Item type code written in a List/array header. Nested-collection items use a fixed marker
    /// (the nested item carries its own header describing its own items, so this 2-byte field only needs
    /// to say "expect a nested list/array here", not fully describe the leaf type).</summary>
    private static string ItemTypeCodeExpr(ItemTypeModel item) => item.Shape switch
    {
        ItemShape.List => "global::MessagingByteSerialization.WellKnownTypeCodes.NestedList",
        ItemShape.Array => "global::MessagingByteSerialization.WellKnownTypeCodes.NestedArray",
        _ => ScalarTypeCodeExpr(item.Scalar!),
    };

    // ----------------------------------------------------------------- FromBytes

    private static void EmitFromBytes(CodeWriter w, TypeModel model)
    {
        using (w.Block($"public static {model.FullyQualifiedName} FromBytes(global::System.ReadOnlySpan<byte> source, out int bytesRead)"))
        {
            MemberModel[] readable = model.Members.Where(static m => !m.IsIgnored).ToArray();
            if (readable.Length == 0)
            {
                w.Line("bytesRead = 0;");
                EmitConstruction(w, model);
                return;
            }

            w.Line("int offset = 0;");
            foreach (MemberModel member in readable)
            {
                EmitReadMember(w, member);
            }

            w.Line("bytesRead = offset;");
            EmitConstruction(w, model);
        }
    }

    /// <summary>
    /// Builds the return value from each member's local (<see cref="LocalVarName"/>), or - for an
    /// <see cref="MemberModel.IsIgnored"/> member, which was never read - <c>default(declared type)</c>.
    /// </summary>
    private static void EmitConstruction(CodeWriter w, TypeModel model)
    {
        if (model.Construction == ConstructionStrategy.PositionalConstructor)
        {
            string args = string.Join(", ", model.Members.Select(static m => m.IsIgnored
                ? $"{m.Name}: default({m.OriginalTypeDisplayName})!"
                : $"{m.Name}: {LocalVarName(m)}"));
            w.Line($"return new {model.FullyQualifiedName}({args});");
        }
        else if (model.Members.Length == 0)
        {
            w.Line($"return new {model.FullyQualifiedName}();");
        }
        else
        {
            w.Line($"return new {model.FullyQualifiedName}");
            w.Line("{");
            w.Indent();
            foreach (MemberModel member in model.Members)
            {
                w.Line(member.IsIgnored
                    ? $"{member.Name} = default({member.OriginalTypeDisplayName})!,"
                    : $"{member.Name} = {LocalVarName(member)},");
            }

            w.Unindent();
            w.Line("};");
        }
    }

    private static void EmitReadMember(CodeWriter w, MemberModel member)
    {
        string finalVarName = LocalVarName(member);
        bool hasCast = member.OriginalTypeDisplayName is not null;
        string varName = hasCast ? finalVarName + "_target" : finalVarName;

        switch (member.Shape)
        {
            case MemberShape.Scalar:
                EmitReadScalar(w, member.Scalar!, varName);
                break;
            case MemberShape.String:
                EmitReadString(w, varName);
                break;
            case MemberShape.List:
                EmitReadCollection(w, member.Element!, varName, isArray: false, depth: 0);
                break;
            case MemberShape.Array:
                EmitReadCollection(w, member.Element!, varName, isArray: true, depth: 0);
                break;
            case MemberShape.Dictionary:
                EmitReadDictionary(w, member.Key!, member.DictionaryValue!, varName);
                break;
        }

        // [ByteSerializableAs<T>]: the read logic above produced a T-shaped value (varName);
        // cast it back to the member's own declared type for the constructor call/initializer below.
        if (hasCast)
        {
            w.Line($"{member.OriginalTypeDisplayName} {finalVarName} = ({member.OriginalTypeDisplayName}){varName};");
        }
    }

    private static void EmitReadScalar(CodeWriter w, ScalarTypeModel scalar, string localName)
    {
        if (scalar.Kind == ScalarKind.NestedByteSerializable)
        {
            w.Line($"{scalar.TypeDisplayName} {localName} = {scalar.NestedTypeFullName}.FromBytes(source.Slice(offset), out int {localName}_read);");
            w.Line($"offset += {localName}_read;");
            return;
        }

        if (scalar.Kind == ScalarKind.Enum)
        {
            EmitReadPrimitive(w, scalar.Primitive, $"{localName}_raw");
            w.Line($"{scalar.TypeDisplayName} {localName} = ({scalar.TypeDisplayName}){localName}_raw;");
            return;
        }

        if (scalar.Kind == ScalarKind.String)
        {
            EmitReadLengthPrefixedString(w, localName);
            return;
        }

        EmitReadPrimitive(w, scalar.Primitive, localName);
    }

    private static void EmitReadPrimitive(CodeWriter w, PrimitiveKind kind, string localName)
    {
        switch (kind)
        {
            case PrimitiveKind.Boolean:
                w.Line($"bool {localName} = source[offset] != 0;");
                break;
            case PrimitiveKind.Byte:
                w.Line($"byte {localName} = source[offset];");
                break;
            case PrimitiveKind.SByte:
                w.Line($"sbyte {localName} = unchecked((sbyte)source[offset]);");
                break;
            case PrimitiveKind.Char:
                w.Line($"char {localName} = (char)global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(offset));");
                break;
            case PrimitiveKind.Decimal:
                w.Line($"decimal {localName};");
                using (w.Scope())
                {
                    w.Line("global::System.Span<int> bits = stackalloc int[4];");
                    w.Line("bits[0] = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset));");
                    w.Line("bits[1] = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset + 4));");
                    w.Line("bits[2] = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset + 8));");
                    w.Line("bits[3] = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset + 12));");
                    w.Line($"{localName} = new decimal(bits);");
                }

                break;
            case PrimitiveKind.Guid:
                w.Line($"global::System.Guid {localName} = new global::System.Guid(source.Slice(offset, 16));");
                break;
            case PrimitiveKind.DateTime:
                w.Line($"global::System.DateTime {localName} = global::System.DateTime.FromBinary(global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(offset)));");
                break;
            case PrimitiveKind.TimeOnly:
                w.Line($"global::System.TimeOnly {localName} = new global::System.TimeOnly(global::System.Buffers.Binary.BinaryPrimitives.ReadInt64LittleEndian(source.Slice(offset)));");
                break;
            default:
                w.Line($"{ClrKeyword(kind)} {localName} = global::System.Buffers.Binary.BinaryPrimitives.Read{kind}LittleEndian(source.Slice(offset));");
                break;
        }

        w.Line($"offset += {kind.Size()};");
    }

    private static void EmitReadString(CodeWriter w, string varName)
    {
        w.Line("offset += 1;"); // CollectionKind.String marker byte, not needed for decoding.
        EmitReadLengthPrefixedString(w, varName);
    }

    /// <summary>Mirror of <see cref="EmitWriteLengthPrefixedString"/>: [4-byte UTF8 byte count][UTF8 bytes].</summary>
    private static void EmitReadLengthPrefixedString(CodeWriter w, string varName)
    {
        string byteCountVar = varName + "_byteCount";
        w.Line($"int {byteCountVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset));");
        w.Line("offset += 4;");
        w.Line($"string {varName} = global::System.Text.Encoding.UTF8.GetString(source.Slice(offset, {byteCountVar}));");
        w.Line($"offset += {byteCountVar};");
    }

    private static void EmitReadCollection(CodeWriter w, ItemTypeModel item, string varName, bool isArray, int depth)
    {
        w.Line("offset += 1;"); // CollectionKind.List/Array marker byte, not needed for decoding.

        string itemCodeVar = varName + "_itemCode";
        w.Line($"ushort {itemCodeVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(offset));");
        w.Line("offset += 2;");
        using (w.Block($"if ({itemCodeVar} != {ItemTypeCodeExpr(item)})"))
        {
            w.Line($"throw new global::System.IO.InvalidDataException($\"Unexpected item type code {{{itemCodeVar}}} while reading '{varName}'.\");");
        }

        string countVar = varName + "_count";
        w.Line($"int {countVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset));");
        w.Line("offset += 4;");

        string elementType = ItemClrTypeDisplay(item);
        w.Line(isArray
            ? $"{elementType}[] {varName} = {ArrayNewExpr(item, countVar)};"
            : $"global::System.Collections.Generic.List<{elementType}> {varName} = new global::System.Collections.Generic.List<{elementType}>({countVar});");

        string indexVar = $"i{depth}";
        using (w.Block($"for (int {indexVar} = 0; {indexVar} < {countVar}; {indexVar}++)"))
        {
            string itemLocal = varName + "_item";
            EmitReadItem(w, item, itemLocal, depth + 1);
            w.Line(isArray ? $"{varName}[{indexVar}] = {itemLocal};" : $"{varName}.Add({itemLocal});");
        }
    }

    /// <summary>Reads a single List/array item, recursing into <see cref="EmitReadCollection"/> when the item is itself a nested collection.</summary>
    private static void EmitReadItem(CodeWriter w, ItemTypeModel item, string localName, int depth)
    {
        if (item.Shape == ItemShape.Scalar)
        {
            EmitReadScalar(w, item.Scalar!, localName);
            return;
        }

        EmitReadCollection(w, item.Element!, localName, isArray: item.Shape == ItemShape.Array, depth);
    }

    /// <summary>Fully-qualified C# display type for an item, recursing for nested collections (e.g. <c>global::System.Collections.Generic.List&lt;int[]&gt;</c>, <c>int[][]</c>).</summary>
    private static string ItemClrTypeDisplay(ItemTypeModel item) => item.Shape switch
    {
        ItemShape.Scalar => item.Scalar!.TypeDisplayName,
        ItemShape.List => $"global::System.Collections.Generic.List<{ItemClrTypeDisplay(item.Element!)}>",
        ItemShape.Array => $"{ItemClrTypeDisplay(item.Element!)}[]",
        _ => "object",
    };

    /// <summary>
    /// Builds the `new` expression for an array whose own element type is <paramref name="elementOfArray"/>.
    /// Jagged array creation syntax only allows a size in the *first* bracket pair - `new int[5][]`, never
    /// `new int[][5]` - so consecutive nested Array levels must have their sizing collapsed onto the
    /// outermost bracket, with the rest left empty. List&lt;T&gt; nesting breaks that chain immediately
    /// (it isn't bracket syntax), so e.g. an array of List&lt;int&gt; just needs a plain single-size `new`.
    /// </summary>
    private static string ArrayNewExpr(ItemTypeModel elementOfArray, string countExpr)
    {
        int extraArrayDepth = 0;
        ItemTypeModel current = elementOfArray;
        while (current.Shape == ItemShape.Array)
        {
            extraArrayDepth++;
            current = current.Element!;
        }

        string innermostType = ItemClrTypeDisplay(current);
        string extraBrackets = string.Concat(Enumerable.Repeat("[]", extraArrayDepth));
        return $"new {innermostType}[{countExpr}]{extraBrackets}";
    }

    private static void EmitReadDictionary(CodeWriter w, ScalarTypeModel key, ItemTypeModel value, string varName)
    {
        w.Line("offset += 1;"); // CollectionKind.Dictionary marker byte, not needed for decoding.

        string keyCodeVar = varName + "_keyCode";
        w.Line($"ushort {keyCodeVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(offset));");
        w.Line("offset += 2;");
        using (w.Block($"if ({keyCodeVar} != {ScalarTypeCodeExpr(key)})"))
        {
            w.Line($"throw new global::System.IO.InvalidDataException($\"Unexpected key type code {{{keyCodeVar}}} while reading '{varName}'.\");");
        }

        string valueCodeVar = varName + "_valueCode";
        w.Line($"ushort {valueCodeVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(source.Slice(offset));");
        w.Line("offset += 2;");
        using (w.Block($"if ({valueCodeVar} != {ItemTypeCodeExpr(value)})"))
        {
            w.Line($"throw new global::System.IO.InvalidDataException($\"Unexpected value type code {{{valueCodeVar}}} while reading '{varName}'.\");");
        }

        string countVar = varName + "_count";
        w.Line($"int {countVar} = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(source.Slice(offset));");
        w.Line("offset += 4;");

        string keyType = key.TypeDisplayName;
        string valueType = ItemClrTypeDisplay(value);
        w.Line($"global::System.Collections.Generic.Dictionary<{keyType}, {valueType}> {varName} = new global::System.Collections.Generic.Dictionary<{keyType}, {valueType}>({countVar});");

        using (w.Block($"for (int i = 0; i < {countVar}; i++)"))
        {
            string keyLocal = varName + "_key";
            string valueLocal = varName + "_value";
            EmitReadScalar(w, key, keyLocal);
            EmitReadItem(w, value, valueLocal, depth: 0);
            w.Line($"{varName}.Add({keyLocal}, {valueLocal});");
        }
    }

    private static string LocalVarName(MemberModel member) => $"value_{member.Name}";

    /// <summary>
    /// Expression that yields the value to serialize for a member. Normally just the member access;
    /// for a <c>[ByteSerializableAs&lt;T&gt;]</c> member it's wrapped in a cast to T, since
    /// Shape/Scalar/Element/Key/DictionaryValue describe T's shape, not the member's own declared type.
    /// </summary>
    private static string MemberAccessor(MemberModel member) => member.OriginalTypeDisplayName is null
        ? $"this.{member.Name}"
        : $"(({member.TargetTypeDisplayName})(this.{member.Name}))";

    private static string ClrKeyword(PrimitiveKind kind) => kind switch
    {
        PrimitiveKind.Boolean => "bool",
        PrimitiveKind.Byte => "byte",
        PrimitiveKind.SByte => "sbyte",
        PrimitiveKind.Int16 => "short",
        PrimitiveKind.UInt16 => "ushort",
        PrimitiveKind.Int32 => "int",
        PrimitiveKind.UInt32 => "uint",
        PrimitiveKind.Int64 => "long",
        PrimitiveKind.UInt64 => "ulong",
        PrimitiveKind.Single => "float",
        PrimitiveKind.Double => "double",
        PrimitiveKind.Char => "char",
        PrimitiveKind.Decimal => "decimal",
        PrimitiveKind.Guid => "global::System.Guid",
        PrimitiveKind.DateTime => "global::System.DateTime",
        PrimitiveKind.TimeOnly => "global::System.TimeOnly",
        _ => "int",
    };
}
